//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasosDePrueba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CasosDePrueba()
        {
            this.CiclosPruebaDetalles = new HashSet<CiclosPruebaDetalle>();
        }
    
        public int id_caso_prueba { get; set; }
        public int id_plan_prueba { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public Nullable<bool> borrado { get; set; }
    
        public virtual PlanesDePrueba PlanesDePrueba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CiclosPruebaDetalle> CiclosPruebaDetalles { get; set; }
    }
}
