//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiclosPruebaDetalle
    {
        public int id_ciclo_prueba_detalle { get; set; }
        public Nullable<int> id_ciclo_prueba { get; set; }
        public Nullable<int> id_caso_prueba { get; set; }
        public Nullable<int> id_usuario_tester { get; set; }
        public Nullable<decimal> cantidad_horas { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public Nullable<bool> aceptado { get; set; }
        public Nullable<bool> borrado { get; set; }
    
        public virtual CasosDePrueba CasosDePrueba { get; set; }
        public virtual CiclosPrueba CiclosPrueba { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
