//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetivosCurso
    {
        public int id_objetivo { get; set; }
        public int id_curso { get; set; }
        public Nullable<int> puntos { get; set; }
        public Nullable<bool> borrado { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Objetivo Objetivo { get; set; }
    }
}
