//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sueldo()
        {
            this.SueldoAsignaciones = new HashSet<SueldoAsignacione>();
            this.SueldoDescuentos = new HashSet<SueldoDescuento>();
        }
    
        public int id_usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal sueldo_bruto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SueldoAsignacione> SueldoAsignaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SueldoDescuento> SueldoDescuentos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
