//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosCursoAvance
    {
        public int id_usuario { get; set; }
        public int id_curso { get; set; }
        public System.DateTime inicio { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public Nullable<int> porc_avance { get; set; }
    
        public virtual UsuariosCurso UsuariosCurso { get; set; }
    }
}
